### ISSUE TITLE
Cloning iit-bigman-ros-pkg takes forever

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/iit-bigman-ros-pkg#1]
We have a weird behavior while trying to clone this repo since it is quite big and probably (with the GIT history) github handles it cutting the download rate on the client.

Any ideas? @arocchi @alaurenzi @EnricoMingo

**Comment by pepperig** [comment]
Try to clone with no histary @liesrock

**Comment by liesrock** [comment]
The problem looks to occur only when IIT network is particularly slow...We should test the clone on a machine outside IIT next time.

**Comment by liesrock** [comment]
It looks like it is only a network problem. Closing it for now.
