### ISSUE TITLE
bigman_multisense.launch in ROS

### ISSUE THREAD

**Issue by dkanou** [ADVRHumanoids/iit-bigman-ros-pkg#3]
@EnricoMingo we need somehow to be able to launch bigman_multisense.launch without the need of yarp_ros_joint_state_publisher, assuming that we have everything from the tf in ROS.

**Comment by liesrock** [comment]
During the Sprint Week we can take care of this task with the simulation tool team.

**Comment by EnricoMingo** [comment]
Yes no problem.

Inviato da iPhone

**Comment by EnricoMingo** [comment]
solved

**Comment by liesrock** [comment]
Great job!
